spring:
    profiles: dev
server:
  servlet:
    context-path: /testing-tool
    path: /api/v1
service:
  message: Dev profile
spring:
  datasource:
    driver: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/testing_tool_dev?useUnicode=true&characterEncoding=utf-8&createDatabaseIfNotExist=true
    username: root
    password: root
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master-dev.yaml